sonar.projectKey=tech-challenge-workshop_execution-service
sonar.organization=tech-challenge-workshop
sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/*.module.ts,**/*.schema.ts,src/main.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
